apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "6868"
      port: 6868
      targetPort: 8080
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
